app/build.gradle, app/src/main/java/com/abatra/android/wheelie/demo/MainActivity.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/values/strings.xml, wheelie/src/main/java/com/abatra/android/wheelie/activity/ResultContracts.java, wheelie/src/main/java/com/abatra/android/wheelie/intent/IntentFactory.java, wheelie/src/test/java/com/abatra/android/wheelie/intent/IntentFactoryTest.java
=> Add open app details screen intent

wheelie/src/main/java/com/abatra/android/wheelie/widget/Toaster.java
=> moved toaster to wheelie

app/src/main/java/com/abatra/android/wheelie/demo/MainActivity.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/values/strings.xml, wheelie/src/main/java/com/abatra/android/wheelie/activity/ResultContracts.java, wheelie/src/main/java/com/abatra/android/wheelie/media/picker/PickMediaRequest.java
=> added pick any image and pick mp4 video result contracts

app/build.gradle, app/src/main/java/com/abatra/android/wheelie/demo/MainActivity.java, wheelie/build.gradle, wheelie/src/main/java/com/abatra/android/wheelie/update/AppUpdateAvailability.java, wheelie/src/main/java/com/abatra/android/wheelie/update/AppUpdateAvailabilityChecker.java, wheelie/src/main/java/com/abatra/android/wheelie/update/AppUpdateCriteriaChecker.java, wheelie/src/main/java/com/abatra/android/wheelie/update/AppUpdateHandler.java, wheelie/src/main/java/com/abatra/android/wheelie/update/AppUpdateRequest.java, wheelie/src/main/java/com/abatra/android/wheelie/update/AppUpdateRequestResult.java, wheelie/src/main/java/com/abatra/android/wheelie/update/AppUpdateRequestor.java, wheelie/src/main/java/com/abatra/android/wheelie/update/AppUpdateType.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/PlayStoreAppUpdateAvailability.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/PlayStoreAppUpdateAvailabilityChecker.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/PlayStoreAppUpdateHandler.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/PlayStoreAppUpdateModule.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/PlayStoreAppUpdateRequest.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/PlayStoreAppUpdateRequestor.java
=> implemeted. need to test UI and write unit tests.

wheelie/src/main/java/com/abatra/android/wheelie/update/AppUpdateRequestor.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/PlayStoreAppUpdateHandler.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/PlayStoreAppUpdateRequestor.java
=> added installDownloadedUpdate method and implementing ILifecycleObserver

wheelie/src/main/java/com/abatra/android/wheelie/update/AppUpdateRequest.java, wheelie/src/main/java/com/abatra/android/wheelie/update/AppUpdateRequestor.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/PlayStoreAppUpdateRequestor.java
=> added checking if app update is downloaded

app/src/main/java/com/abatra/android/wheelie/demo/MainActivity.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/values/strings.xml, wheelie/src/main/java/com/abatra/android/wheelie/thread/SaferTask.java, wheelie/src/main/java/com/abatra/android/wheelie/update/AppUpdateCriteria.java, wheelie/src/main/java/com/abatra/android/wheelie/update/AppUpdateRequest.java, wheelie/src/main/java/com/abatra/android/wheelie/update/AppUpdateRequestor.java, wheelie/src/main/java/com/abatra/android/wheelie/update/AppUpdateType.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/PlayStoreAppUpdateAvailability.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/PlayStoreAppUpdateAvailabilityChecker.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/PlayStoreAppUpdateHandler.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/PlayStoreAppUpdateModule.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/PlayStoreAppUpdateRequestor.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/fake/DownloadFailsFlexibleFakePlayStoreAppUpdateRequestor.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/fake/DownloadFakePlayStoreAppUpdateRequestor.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/fake/FakePlayStoreAppUpdateHandlerFactory.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/fake/FakePlayStoreAppUpdateRequestor.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/fake/FlexibleFakePlayStoreAppUpdateRequestor.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/fake/ImmediateFakePlayStoreAppUpdateRequestor.java, wheelie/src/main/java/com/abatra/android/wheelie/update/playstore/fake/InstallFailsFlexibleFakePlayStoreAppUpdateRequestor.java, wheelie/src/test/java/com/abatra/android/wheelie/update/playstore/PlayStoreAppUpdateAvailabilityCheckerTest.java, wheelie/src/test/java/com/abatra/android/wheelie/update/playstore/PlayStoreAppUpdateRequestorTest.java
=> In app updates

wheelie/src/main/java/com/abatra/android/wheelie/resource/SpannableStringBuilderText.java, wheelie/src/test/java/com/abatra/android/wheelie/resource/SpannableStringBuilderTextTest.java
=> added impl

.idea/dictionaries/abatra.xml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/abatra/android/wheelie/demo/MainActivity.java, app/src/main/java/com/abatra/android/wheelie/demo/SettingsActivity.java, app/src/main/java/com/abatra/android/wheelie/demo/SettingsFragment.java, app/src/main/res/drawable/ic_baseline_cameraswitch_24.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_settings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences_main.xml, wheelie/src/main/java/com/abatra/android/wheelie/preferences/PreferenceUtils.java
=> tint-pref-icons-fix

wheelie/src/main/java/com/abatra/android/wheelie/lifecycle/ResourceMutableLiveData.java
=> added methods to set resource from bolts tasks

wheelie/src/main/java/com/abatra/android/wheelie/lifecycle/ResourceLiveData.java, wheelie/src/main/java/com/abatra/android/wheelie/lifecycle/ResourceLiveDataApi.java, wheelie/src/main/java/com/abatra/android/wheelie/lifecycle/ResourceMediatorLiveData.java
=> added resource mediator live data

app/src/main/java/com/abatra/android/wheelie/demo/MainActivity.java, wheelie/src/main/AndroidManifest.xml, wheelie/src/main/java/com/abatra/android/wheelie/lifecycle/Resource.java, wheelie/src/main/java/com/abatra/android/wheelie/network/InternetConnectionObserver.java, wheelie/src/main/java/com/abatra/android/wheelie/network/PreQInternetConnectionObserver.java, wheelie/src/main/java/com/abatra/android/wheelie/network/QOrAboveInternetConnectionObserver.java
fixes #120 
fixes #123 
fixes #124
=> Fixed 4.28.1 milestone issues.

wheelie/src/main/java/com/abatra/android/wheelie/lifecycle/Resource.java, wheelie/src/test/java/com/abatra/android/wheelie/lifecycle/ResourceTest.java
=> Added isLoading, isLoaded and isFailed methods to Resource class

.idea/dictionaries/abatra.xml, wheelie/src/main/java/com/abatra/android/wheelie/app/ApplicationInitializers.java, wheelie/src/main/java/com/abatra/android/wheelie/app/WheelieApplication.java, wheelie/src/main/java/com/abatra/android/wheelie/startup/ApplicationInitializer.java, wheelie/src/test/java/com/abatra/android/wheelie/app/ApplicationInitializersTest.java, wheelie/src/test/java/com/abatra/android/wheelie/app/WheelieApplicationTest.java
=> Added application initializers and a base app for initializing them.

app/src/main/java/com/abatra/android/wheelie/demo/RecyclerViewAdapterDemoActivity.java, wheelie/src/main/java/com/abatra/android/wheelie/recyclerview/adapter/AbstractAdapter.java, wheelie/src/main/java/com/abatra/android/wheelie/recyclerview/adapter/Adapter.java, wheelie/src/main/java/com/abatra/android/wheelie/recyclerview/adapter/selection/SelectionRecyclerViewAdapter.java
=> added method to set items using diff result

build.gradle
=> apply jitpack plugin to publish library artifacts

network/src/main/AndroidManifest.xml
=> Add CHANGE_NETWORK_STATE permission for internet connectivity checker.

build.gradle, core/src/main/java/com/abatra/android/wheelie/core/async/RunnableTrackerHandler.java
=> Changed the code to CopyOnWriteArraySet

architecture/src/main/java/com/abatra/android/wheelie/architecture/LoadViewStateEvent.java, build.gradle, core/src/main/java/com/abatra/android/wheelie/core/content/Intents.java, may-i/src/main/java/com/abatra/android/wheelie/mayI/AbstractSinglePermissionRequestor.java, may-i/src/main/java/com/abatra/android/wheelie/mayI/ManageOverlayPermissionRequestor.java, may-i/src/main/java/com/abatra/android/wheelie/mayI/ManifestSinglePermissionRequestor.java, may-i/src/test/java/com/abatra/android/wheelie/mayI/AbstractSinglePermissionRequestorTest.java, may-i/src/test/java/com/abatra/android/wheelie/mayI/ManifestSinglePermissionRequestorTest.java
=> Fixed bugs for 5.2.3

core/src/main/java/com/abatra/android/wheelie/core/media/ImageConverter.java
=> Rewind buffer before copying pixels in bitmap.

core/src/main/java/com/abatra/android/wheelie/core/media/ImageConverter.java, core/src/main/java/com/abatra/android/wheelie/core/media/YuvToRgbImageConverter.java
=> Replaced existing image converter with sample code from android repo.
